## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: required

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

git:
  depth: 50

# safelist
branches:
  only:
  - develop

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
     update: true
     packages:
     - gfortran
     - gcc
     - liblapack-dev

before_install:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew install gcc;
    brew link --overwrite gcc;
  fi

## uncomment the following lines to override the default test script
#script:
#- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#- julia -e 'Pkg.clone(pwd()); Pkg.build("AndersonMoore"); Pkg.test("AndersonMoore"; coverage=true)'

after_success:
#-  julia -e 'cd(Pkg.dir("AndersonMoore")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
 - |
   julia -e 'cd(Pkg.dir("AndersonMoore"))
	     Pkg.add("Coverage")
             using Coverage
             Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
